#!/bin/bash

to_wait="tempfile"
interval=1
max_loops=300

touch "$to_wait"

while true
do
    if [ -f "$to_wait" ]; then
        echo "File exists."
        sleep "$interval"
    else
        exit 0
    fi

    max_loops=$((max_loops-1))

    if [ "$max_loops" -eq 0 ]; then
        echo "Wait expired!"
        exit 1
    fi
done
